### PR TITLE
UseR proposal thoughts

### PR DESCRIPTION
**Pull request by emilyriederer**
Thank you so much for writing this, @statnmap ! This looks fantastic. 

I only propose one small change, but instead I have a number of thoughts and questions for you:

- For the title, we can certainly use "Rmd First" like your blog post instead of mine if you would prefer! In the past, I've emphasized that "your end result doesn't have to be a package", so "Rmd First" is perhaps even more clear that our goal is _definitely_ a package here! Please use whichever you prefer
- For the learning goals, what are you thinking for "know how to share their work with the community"? Do you think we should cover GitHub? CRAN? `tar` files? 
-  Do you have any tentative vision for how we will break topics across 3 hours? I suspect we could perhaps do it in two hours but, then again, I never leave enough time for anything (😆). As I think about how to break out the content, I suppose we could do:
    + Breaking Rmd into functions / Migrating modular components to package structure / Re-doing process with `fusen`
    + Overview of process (*not sure what exercises would be then - perhaps working in groups to understand a sample Rmd and deciding what parts are specific to one analysis vs what parts are generally applicable?*) / Implementation / Re-doing process with `fusen`
    + Something else
- Should we have function *writing* be an explicit prerequisite? I don't know if there is a risk that if we try to cover everything from writing one's first functions to writing one's first packages all at once, we might move too fast and confuse learners
- Do we need to require microphones? Hopefully most everyone has them, but people could also ask questions via Slack, etc. so I would hate for this to completely be a barrier for someone
- Wow! ThinkR's tutorial platform looks fantastic

### CODE REVIEW

**Comment by emilyriederer** [comment]
For further discussion on Monday, I thought I'd try to list out a more granular set of things that we could cover and we can decide yes/no how much time to spend on each. This list is very much *not* a proposal and I think certain covers more things that we should, but I thought perhaps we could start overly comprehensive and work our way backwards. This can help us decide on timing.

- [ ]  Writing functions
- [ ] Subjective (perhaps from tidyverse?) function design principles
- [ ]  Writing `roxygen2` documentation
- [ ]  Writing tests for functions with `testthat` 
- [ ]  Managing function dependencies (in roxygen and DESCRIPTION)
- [ ]  Advanced function concepts (default arguments, ellipsis)
- [ ]  Problems / nuances when turning tidyverse code into function (`.data` pronoun)
- [ ] R Markdown parameters (as intermediary step before package)
- [ ] `source()`ing separate function files into a project (as intermediary step before package)
- [ ] R projects (as intermediary stage to package)
- [ ] R-specific data formats (`Rdata`, `Rds`)
- [ ] File structure of an R package
- [ ] `usethis` package (does this make sense if we teach `fusen`?)
- [ ] Making documentation websites with `pkgdown` 
- [ ] "Advanced" function components like templates, add-ins
- [ ] `fusen` package
- [ ] Sharing a package on CRAN
- [ ] Sharing a package as a `tar` file
- [ ] Sharing a package on GitHub 
- [ ] Hosting a package website on GitHub
- [ ] Automating testing with GitHub Actions

**Comment by statnmap** [comment]
I put the notes in the Wiki: https://github.com/statnmap/user2021.rmdd/wiki/Meetings

**Comment by emilyriederer** [comment]
Hey @statnmap ! I just committed a few small wording changes to the proposal. Please feel free to keep or revert as you see fit. Nice talking to you today!

**Comment by statnmap** [comment]
Tutorial submitted ! :crossed_fingers:

**Comment by emilyriederer** [comment]
Thanks @statnmap ! And now we wait 🙂

**Pull request merged**
